### ISSUE TITLE
Interpreter frames

### ISSUE THREAD

**Issue by brendangregg** [jrudolph/perf-map-agent#6]
I often see "Interpreter" frames. I think I was expecting more symbols.

```
   100.00%     java  perf-20844.map  [.] Interpreter
               |
               --- Interpreter
                   Interpreter
                   Interpreter
                   Interpreter
                   call_stub
                   JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)
                   jni_invoke_static(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*)
                   jni_CallStaticVoidMethod
                   JavaMain
                   start_thread
```

**Comment by zeocio** [comment]
One possibility is to run (obviously only oracle jdk) JFR stack sampling and perf stack sampling at the same time and use an external tool to merge the 2 data sets to provide greater granularity where interpreted frames are present. I came across this recently: https://github.com/chrishantha/jfr-flame-graph

**Comment by toaler** [comment]
Resolving the Interpreter frames is still useful, in applications with a high amount of total paths, not understanding the interpreted frames can be very time consuming for the engineer to work out the subsuming methods that are dominating the calls to the known jitted frames.

We were looking for a solution on MacOS that allows us to get all JVM stacks (jit, gc, application code) as well as resolving all frames (JVM, Java interpreter/native, libaries, etc).  dtrace + perf-map-agent is great for this, other than the tradeoff on not being able to get the interpreted frames.  async-profiler/honest-profiler can resolve the interpreted frames.  I suppose it's easier for getAsyncCallTrace to resolve the interpreted code as it's running in the same context that has that metadata, where dtrace doesn't have the luxury.

Since we are interested in OSX native invocations, honest-profiler is out of the mix.  async-profiler can acquire interpreted/native frames as well on MacOS, however it has a overhead when using it to evaluate JVM startup times, which we are interested in.

Anyways thanks for added the dtrace scripts as they are proving to be very useful.

**Comment by squito** [comment]
Getting more info from the interpreter frames would also be useful with `bcc`'s `trace`, which also takes advantage of this file.  I'm trying to track the source of large malloc calls, eg.   `trace -p [pid] -K -U -a 'c:malloc "size = %d", arg1'`.  Those calls aren't necessarily so frequently (something is allocating a lot of memory into its own internal pool).  Maybe there is a better way to do this directly in `trace`?

In any case, I can understand why this is hard to do

**Comment by apangin** [comment]
@squito The neighbor project [async-profiler](https://github.com/jvm-profiling-tools/async-profiler) is already capable of doing what you want. It traces `malloc` calls in `-e malloc` mode and records allocation size along with the mixed stack trace: native + Java, including interpreter frames. Please open a ticket there if you need help in getting this work.

**Comment by squito** [comment]
awesome, thanks @apangin , I will check it out!
